name: Github Actions Demo

on:
  push:
    branches: ["main", "dev"]


jobs:
  demo:
    name: Kör demo
    runs-on: ubuntu-latest

    steps:
       - name: 1. hello
         run: echo "Hej användare!"

       - name: 2. Show enviroment
         run: |
           echo "Körs på repository: ${{ github.repository }}"
           echo "Trigger: ${{ github.event_name }}"
       
       - name: 3. checkout repo
         uses: actions/checkout@v7

       - name: 4. list files
         run: |
           ls -al
           cd .github/workflows
           ls -al

       - name: 5. Kör Kontroller
         run: bash scripts/check.sh

       - name: 6. Visa projektinformation
         run: bash scripts/project-info.sh

