name: Github Actions Demo

on:
  push:
    branches: ["main", "dev"]


jobs:
  demo:
    name: Kör demo
    runs-on: ubuntu-latest

    steps:
       - name: 1. hello
         run: echo "Hej användare!"

       - name: 2. Show enviroment
         run: |
           echo "Körs på repository: ${{ github.repository }}"
           echo "Trigger: ${{ github.event_name }}"
       
       - name: checkout repo
         uses: actions/checkout@v4

       - name: 4. list files
         run: |
           ls -al
           cd .github/workflows
           ls -al
