name: Pull Request Demo

on:
  pull_request:
    branches: ["main"]

jobs:
  demo:
    name: Kör PR-demo
    runs-on: ubuntu-latest

    steps:
      - name: 1. Hello
        run: echo "Den här workflowen kördes av en Pull Request!"

      - name: 2. show enviroment
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Trigger: ${{ github.event_name }}"

      - name: 3. checkout repo
        uses: actions/checkout@v7

      - name: 4. List files
        run: ls -al

      - name: 5. Kör kontroller
        run: bash scripts/check.sh

